service: serverless-wedding

provider:
  name: aws
  runtime: rust
  stage: dev
  memorySize: 128

package:
  individually: true

plugins:
  - serverless-rust

functions:
  create:
    handler: hello
    events:
      - http:
          path: /
          method: GET
