service: serverless-wedding-api
provider:
  name: aws
  runtime: rust
  memorySize: 128
  role: ${file(../serverless-wedding-infrastructure/output.json):api_role_arn.value}
  environment:
    RSVP_TABLE_NAME: ${file(../serverless-wedding-infrastructure/output.json):rsvp_table_name.value}

package:
  individually: true

plugins:
  - serverless-rust

functions:
  household-get:
    handler: serverless-wedding-api.read
    events:
      - http:
          path: /household
          method: get
          cors: true

  household-create:
    handler: serverless-wedding-api.batch-create
    events:
      - http:
          path: /household
          method: post
          cors: true
