service: serverless-wedding-api
provider:
  name: aws
  runtime: rust
  memorySize: 128
  role: ${file(../serverless-wedding-infrastructure/output.json):api_role_arn.value}
  environment:
    RSVP_TABLE_NAME: ${file(../serverless-wedding-infrastructure/output.json):rsvp_table_name.value}

package:
  individually: true

plugins:
  - serverless-rust

functions:
  read:
    handler: read
    events:
      - http:
          path: /
          method: get
          cors: true

  create:
    handler: create
    events:
      - http:
          path: /
          method: post
          cors: true
