service: serverless-wedding-api
provider:
  name: aws
  runtime: rust
  memorySize: 128

package:
  individually: true

plugins:
  - serverless-rust

functions:
  read:
    handler: read
    events:
      - http:
          path: /
          method: get
          cors: true

  create:
    handler: create
    events:
      - http:
          path: /
          method: post
          cors: true
