service: serverless-wedding-api
provider:
  name: aws
  runtime: rust
  memorySize: 128
  role: ${file(../serverless-wedding-infrastructure/output.json):api_role_arn.value}
  environment:
    RSVP_TABLE_NAME: ${file(../serverless-wedding-infrastructure/output.json):rsvp_table_name.value}

package:
  individually: true

plugins:
  - serverless-rust

functions:
  household-get:
    handler: serverless-wedding-api.household-get
    events:
      - http:
          path: /household/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  household-create:
    handler: serverless-wedding-api.household-create
    events:
      - http:
          path: /household
          method: post
          cors: true

  rsvp-patch:
    handler: serverless-wedding-api.rsvp-patch
    events:
      - http:
          path: /rsvp
          method: patch
          cors: true
          request:
            parameters:
              paths:
                id: true
