service: serverless-wedding

provider:
  name: aws
  runtime: python3.6
  stage: dev
  memorySize: 128
  environment:
    RSVP_TABLE_NAME: ${file(../serverless-wedding-infrastructure/output.json):rsvp_table_name.value}

plugins:
  - serverless-rust

custom:
  rust:
    cargoFlags: '--features lando/python3-sys'

package:
  individually: true
  exclude:
    - ./**

functions:
  create:
    handler: liblambda.create
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/rsvp/'
          method: POST

  read:
    handler: liblambda.read
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/rsvp/'
          method: GET

  update:
    handler: liblambda.update
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/rsvp/'
          method: PUT

  delete:
    handler: liblambda.delete
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/rsvp/'
          method: delete